<script lang="ts">
  import { open, save } from '@tauri-apps/plugin-dialog';
  import { api, type Candidate, type Inspection, type Preview, type Route, type SaveReceipt, type Snapshot } from '$lib/api';

  let sessionId = $state<string>(); let endpoint = $state(''); let dimension = $state(0);
  let snapshot = $state<Snapshot>(); let route = $state<Route>(); let oudiaPath = $state(''); let inspection = $state<Inspection>();
  let diagramIndex = $state<number>(); let trainType = $state<number>(); let candidates = $state<Candidate[]>([]); let candidate = $state<Candidate>();
  let manualMode = $state(false); let manualSlots = $state<(number | undefined)[]>([]);
  let preview = $state<Preview>(); let policy = $state('preserve'); let outputPath = $state(''); let receipt = $state<SaveReceipt>();
  let busy = $state(''); let error = $state(''); let generation = 0;
  const dimText = (value: unknown) => typeof value === 'string' ? value : JSON.stringify(value);
  const milliseconds = (value: number | undefined) => value === undefined ? 'なし' : `${value} ms`;
  const selectedTemplate = () => inspection?.templates.find((item) => item.diagram_index === candidate?.diagram_index && item.train_index === candidate?.train_index);
  const automaticCandidates = () => candidates.filter((item) => !item.manual_only);
  function manualIssues(): string[] {
    if (!route || !candidate || !manualMode) return [];
    const slots = selectedTemplate()?.active_station_slots ?? [];
    const values = manualSlots.filter((value): value is number => value !== undefined);
    const issues: string[] = [];
    if (route.station_count !== slots.length) issues.push(`MTR 駅数 ${route.station_count} と対象列車の有効駅スロット数 ${slots.length} が一致しません。`);
    if (values.length !== route.station_count) issues.push('すべての MTR 駅に OuDia スロットを選択してください。');
    if (new Set(values).size !== values.length) issues.push('同じ OuDia スロットを複数の駅へ割り当てることはできません。');
    return issues;
  }
  function resetFromSnapshot() { route = undefined; candidates = []; candidate = undefined; manualMode = false; manualSlots = []; preview = undefined; receipt = undefined; }
  function resetFromRoute() { candidates = []; candidate = undefined; manualMode = false; manualSlots = []; preview = undefined; receipt = undefined; }
  function resetFromOudia() { diagramIndex = undefined; trainType = undefined; resetFromRoute(); }
  function chooseCandidate(item: Candidate) { candidate = item; manualMode = item.manual_only; manualSlots = route ? Array.from({ length: route.station_count }, (_, index) => item.station_mappings.find((mapping) => mapping.mtr_station_index === index)?.oudia_station_slot) : []; preview = undefined; }
  function toggleManual() { manualMode = !manualMode; if (manualMode && route) manualSlots = Array.from({ length: route.station_count }, (_, index) => candidate?.station_mappings.find((mapping) => mapping.mtr_station_index === index)?.oudia_station_slot); preview = undefined; }
  async function task(label: string, action: () => Promise<void>) { const current = ++generation; busy = label; error = ''; try { await action(); } catch (e) { if (current === generation) error = e instanceof Error ? e.message : String(e); } finally { if (current === generation) busy = ''; } }
  function requireDesktop(): boolean { if (typeof window !== 'undefined' && !('__TAURI_INTERNALS__' in window)) { error = 'Tauri デスクトップアプリで開いてください。ブラウザーではファイルを選択できません。'; return false; } return true; }
  function detect() { return task('MTR API を自動検出中です。', async () => { const [id, endpoints] = await api.detect(sessionId); sessionId = id; if (!endpoints.length) throw new Error('MTR APIを検出できませんでした。手動 URL を入力してください。'); endpoint = endpoints[0].url; if (endpoints.length > 1) error = `接続先候補が ${endpoints.length} 件あります。手動 URL を確認してください。`; }); }
  function fetchSnapshot() { if (!sessionId) { error = '先に自動検出を行うか、接続先を確認してください。'; return; } return task('MTR スナップショットを取得中です。', async () => { snapshot = await api.snapshot(sessionId!, endpoint, dimension); resetFromSnapshot(); }); }
  async function chooseOudia() { if (!requireDesktop()) return; const selected = await open({ multiple: false, filters: [{ name: 'OuDia', extensions: ['oud2'] }] }); if (typeof selected === 'string' && sessionId) { oudiaPath = selected; await task('OuDia ファイルを解析中です。', async () => { inspection = await api.inspect(sessionId!, oudiaPath); resetFromOudia(); }); } }
  function findCandidates() { if (!sessionId || !route || !inspection) return; task('経路候補を検索中です。', async () => { candidates = await api.candidates(sessionId!, route!.id, diagramIndex, trainType); candidate = undefined; manualMode = false; manualSlots = []; preview = undefined; }); }
  function buildPreview() { if (!sessionId || !candidate || manualIssues().length) return; const mappings = manualMode ? manualSlots.map((slot, index) => ({ mtr_station_index: index, oudia_station_slot: slot! })) : undefined; task('時刻プレビューを生成中です。', async () => { preview = await api.preview(sessionId!, candidate!.id, mappings); policy = 'preserve'; receipt = undefined; }); }
  async function chooseOutput() { if (!requireDesktop()) return; const selected = await save({ filters: [{ name: 'OuDia', extensions: ['oud2'] }] }); if (typeof selected === 'string') outputPath = selected; }
  function saveFile() { if (!sessionId || !preview || !outputPath) return; task('安全な保存と検証を実行中です。', async () => { receipt = await api.save(sessionId!, preview!.id, outputPath, policy); }); }
</script>

<a class="skip" href="#wizard">手順へ移動</a>
<main class="page" id="wizard" aria-busy={busy !== ''}>
  <h1>MTR 基準時分を OuDia へ反映</h1>
  {#if busy}<p class="notice" role="status">{busy}</p>{/if}{#if error}<p class="notice error" role="alert">エラー: {error}</p>{/if}
  <section class="step" aria-labelledby="step1"><h2 id="step1">1. MTR 接続</h2><div class="fields"><button onclick={detect} disabled={busy !== ''}>自動検出</button><label>API URL <input bind:value={endpoint} inputmode="url" placeholder="http://127.0.0.1/" /></label><label>dimension <input type="number" min="0" bind:value={dimension} /></label><button onclick={fetchSnapshot} disabled={busy !== '' || !endpoint}>接続</button></div>{#if snapshot}<p role="status">接続先: {endpoint} / 取得路線数: {snapshot.routes.length} / API 時刻: {snapshot.api_current_time_millis} ms</p>{:else}<p class="muted">未接続です。自動検出が失敗した場合は loopback URL を入力してください（例: http://127.0.0.1/、http://127.0.0.1:49182/）。</p>{/if}</section>
  <section class="step" aria-labelledby="step2"><h2 id="step2">2. dimension 選択</h2>{#if snapshot}{#if snapshot.dimensions.length > 1}<label>dimension <select bind:value={dimension} onchange={fetchSnapshot}>{#each snapshot.dimensions as item}<option value={Number(item)}>{dimText(item)}</option>{/each}</select></label>{:else}<p>dimension: {snapshot.dimensions.length === 1 ? dimText(snapshot.dimensions[0]) : '取得対象外'}（1 件は自動選択）</p>{/if}{:else}<p class="muted">接続後に選択できます。</p>{/if}</section>
  <section class="step" aria-labelledby="step3"><h2 id="step3">3. MTR 路線選択</h2>{#if snapshot}<label>路線 <select bind:value={route} onchange={resetFromRoute}><option value={undefined}>選択してください</option>{#each snapshot.routes as item}<option value={item}>{item.name}</option>{/each}</select></label>{#if route}<p>駅数: {route.station_count} / 総運転時分: {milliseconds(route.total_run_millis)} / 総停車時分: {milliseconds(route.total_dwell_millis)}</p><ol>{#each route.stations as station}<li>{station.station_name}（ホーム: {station.platform_name || '記載なし'} / 停車: {milliseconds(station.dwell_millis)} / 次駅まで: {milliseconds(station.run_millis_to_next)}）</li>{/each}</ol>{/if}{:else}<p class="muted">接続後に選択できます。</p>{/if}</section>
  <section class="step" aria-labelledby="step4"><h2 id="step4">4. OuDia ファイル選択</h2><div class="fields"><label>OuDia ファイル <input readonly value={oudiaPath} aria-label="選択した OuDia ファイル" /></label><button onclick={chooseOudia} disabled={!sessionId || busy !== ''}>.oud2 を選択</button></div>{#if inspection}<p>路線名: {inspection.line_name || '記載なし'} / FileType: {inspection.file_type} / 基準ダイヤ: {inspection.kijun_status} / diagram 数: {inspection.diagrams.length} / 駅数: {inspection.station_count} / Lossless 解析: 成功</p>{/if}</section>
  <section class="step" aria-labelledby="step5"><h2 id="step5">5. 列車種別・経路選択</h2>{#if inspection && route}<fieldset><legend>テンプレート条件</legend><div class="fields"><label>ダイヤ <select bind:value={diagramIndex} onchange={resetFromRoute}><option value={undefined}>Application に任せる</option>{#each inspection.diagrams as d}<option value={d.index}>{d.index}（列車 {d.train_count} 本）</option>{/each}</select></label><label>列車種別 <select bind:value={trainType} onchange={resetFromRoute}><option value={undefined}>指定しない</option>{#each inspection.train_types as type}<option value={type}>{type}</option>{/each}</select></label><button onclick={findCandidates} disabled={busy !== ''}>経路候補を検索</button></div></fieldset>{#if candidates.length}{#if automaticCandidates().length === 0}<p class="notice warning" role="status">自動照合候補は 0 件です。下の既存列車を選択して手動駅対応を行ってください。</p>{/if}<fieldset><legend>対象列車を選択（{candidates.length} 件）</legend>{#each candidates as item}<label><input type="radio" name="candidate" checked={candidate?.id === item.id} onchange={() => chooseCandidate(item)} /> {item.direction} / {item.rank} {item.manual_only ? '（手動対応用）' : ''} / スロット列: {item.station_mappings.map(m => m.oudia_station_slot).join(', ') || '手動選択'}</label>{/each}</fieldset>{:else}<p class="notice warning" role="status">この条件に一致する既存列車がありません。ダイヤまたは列車種別を選択し直してください。</p>{/if}{:else}<p class="muted">路線と OuDia ファイルを選択してください。</p>{/if}</section>
  <section class="step" aria-labelledby="step6"><h2 id="step6">6. 駅対応確認</h2>{#if candidate && route && selectedTemplate()}<label><input type="checkbox" checked={manualMode} disabled={candidate.manual_only} onchange={toggleManual} /> 手動で修正する</label><table><thead><tr><th>MTR 駅</th><th>MTR ホーム</th><th>OuDia スロット</th></tr></thead><tbody>{#each route.stations as station, index}<tr><td>{station.station_name}</td><td>{station.platform_name || '記載なし'}</td><td>{#if manualMode}<label>{station.station_name}<select value={manualSlots[index] ?? ''} onchange={(event) => { manualSlots[index] = event.currentTarget.value === '' ? undefined : Number(event.currentTarget.value); manualSlots = [...manualSlots]; }}><option value="">選択してください</option>{#each selectedTemplate()!.active_station_slots as slot}<option value={slot.index}>{slot.index}: {slot.name || '記載なし'}（前: {slot.previous_name || 'なし'} / 後: {slot.next_name || 'なし'}）</option>{/each}</select></label>{:else}{@const mapping = candidate.station_mappings.find((item) => item.mtr_station_index === index)}{mapping ? `${mapping.oudia_station_slot}: ${selectedTemplate()!.active_station_slots.find((slot) => slot.index === mapping.oudia_station_slot)?.name || '記載なし'}` : '未選択'}{/if}</td></tr>{/each}</tbody></table>{#each manualIssues() as issue}<p class="notice warning" role="alert">確認が必要です: {issue}</p>{/each}<button onclick={buildPreview} disabled={busy !== '' || manualIssues().length !== 0 || (!manualMode && candidate.station_mappings.length !== route.station_count)}>全駅対応を確認してプレビューへ</button>{:else}<p class="muted">対象列車を選択してください。</p>{/if}</section>
  <section class="step" aria-labelledby="step7"><h2 id="step7">7. 時刻プレビュー</h2>{#if preview}<p>基準始発時刻: <strong>{preview.fixed_base_time}（固定）</strong></p><div class="table"><table><thead><tr><th>駅</th><th>既存着</th><th>既存発</th><th>新着</th><th>新発</th><th>raw ms</th><th>run / dwell ms</th></tr></thead><tbody>{#each preview.stops as stop}<tr><td>{stop.station}</td><td>{stop.existing_arrival ?? '記載なし'}</td><td>{stop.existing_departure ?? '記載なし'}</td><td>{stop.rounded_arrival ?? '-'}</td><td>{stop.rounded_departure ?? '-'}</td><td>{stop.raw_arrival_millis ?? '-'} / {stop.raw_departure_millis ?? '-'}</td><td>{stop.run_millis ?? '-'} / {stop.dwell_millis}</td></tr>{/each}</tbody></table></div>{#each preview.warnings as warning}<p class="notice warning" role="alert">警告: {warning}</p>{/each}{:else}<p class="muted">駅対応を確認後に生成します。</p>{/if}</section>
  <section class="step" aria-labelledby="step8"><h2 id="step8">8. Operation 選択</h2>{#if preview?.operation_present}<fieldset><legend>Operation 情報が存在します</legend><label><input type="radio" value="preserve" bind:group={policy} /> 元のまま保持する（意味上の整合性は保証されません）</label><label><input type="radio" value="remove_target_train" bind:group={policy} /> 対象列車から削除する</label></fieldset>{:else}<p>Operation 情報はありません。</p>{/if}</section>
  <section class="step" aria-labelledby="step9"><h2 id="step9">9. 保存</h2><div class="fields"><label>出力先 <input readonly value={outputPath} aria-label="出力先" /></label><button onclick={chooseOutput} disabled={!preview || busy !== ''}>出力先を選択</button><button onclick={saveFile} disabled={!outputPath || !preview || busy !== ''}>保存</button></div><p>変更対象: EkiJikoku 時刻部分のみ。元ファイルは上書きせず、既存出力先は拒否します。</p>{#if receipt}<p class="notice success" role="status">保存しました: {receipt.output_path}（{receipt.bytes} bytes、SHA-256: {receipt.sha256}）</p>{/if}</section>
</main>
